export enum NotificationEvent {
  ORGANIZATION_CREATED = 'OrganizationCreatedEvent',
  ORGANIZATION_MEMBER_INVITED = 'OrganizationMemberInvitedEvent',
  ORGANIZATION_MEMBER_JOINED = 'OrganizationMemberJoinedEvent',
  ORGANIZATION_PROJECT_CREATED = 'OrganizationProjectCreatedEvent',
  ISSUE_CLOSED = 'IssueClosedEvent',
  ISSUE_COMMENT_CONTENT_CHANGED = 'IssueCommentContentChangedEvent',
  ISSUE_COMMENTED = 'IssueCommentedEvent',
  ISSUE_COMMENT_HIDDEN = 'IssueCommentHiddenEvent',
  ISSUE_COMMENT_VOTED = 'IssueCommentVotedEvent',
  ISSUE_CONTENT_CHANGED = 'IssueContentChangedEvent',
  ISSUE_OPENED = 'IssueOpenedEvent',
  ISSUE_RENAMED = 'IssueRenamedEvent',
  ISSUE_TYPE_CHANGED = 'IssueTypeChangedEvent',
  ISSUE_VOTED = 'IssueVotedEvent',
}
