export enum NotificationEvent {
  ORGANIZATION_CREATED_EVENT = 'OrganizationCreatedEvent',
  // ORGANIZATION_MEMBER_INVITED_EVENT = 'OrganizationMemberInvitedEvent',
  // ORGANIZATION_MEMBER_JOINED_EVENT = 'OrganizationMemberJoinedEvent',
  // ORGANIZATION_PROJECT_CREATED_EVENT = 'OrganizationProjectCreatedEvent',
  // ISSUE_CLOSED_EVENT = 'IssueClosedEvent',
  // ISSUE_COMMENT_CONTENT_CHANGED_EVENT = 'IssueCommentContentChangedEvent',
  // ISSUE_COMMENTED_EVENT = 'IssueCommentedEvent',
  // ISSUE_COMMENT_HIDDEN_EVENT = 'IssueCommentHiddenEvent',
  // ISSUE_COMMENT_VOTED_EVENT = 'IssueCommentVotedEvent',
  // ISSUE_CONTENT_CHANGED_EVENT = 'IssueContentChangedEvent',
  // ISSUE_OPENED_EVENT = 'IssueOpenedEvent',
  // ISSUE_RENAMED_EVENT = 'IssueRenamedEvent',
  // ISSUE_TYPE_CHANGED_EVENT = 'IssueTypeChangedEvent',
  // ISSUE_VOTED_EVENT = 'IssueVotedEvent',
}
