export enum ApplicationErrorCode {
  GENERIC_VALIDATION_FAILED = 'GENERIC_2',
  GENERIC_EMAIL_UNAVAILABLE = 'GENERIC_3',
  USER_INVALID_ACTIVATION_TOKEN = 'USER_1',
  USER_ALREADY_ACTIVATED = 'USER_2',
  USER_DOES_NOT_EXIST = 'USER_3',
}
